name: Must run on custom runner

#on: push

on:
 workflow_dispatch:

jobs:
  init:
    runs-on: self-hosted
    steps:
      - run: echo 'hello cloud gurus'
      - run: cd /runners/custom-runner && git checkout dev
      - run: echo $HOSTNAME
      - run: pwd
      - run: bash /runners/custom-runner/dev/mostrar.sh
      - run: cd /runners/custom-runner/dev && bash ./mostrar.sh
      - run: cd /runners/custom-runner && sudo docker build -t flaskapi .
      - run: pwd
