name: Must run on custom runner

#on: push

on:
 workflow_dispatch:

jobs:
  init:
    runs-on: self-hosted
    steps:
      - run: echo 'hello cloud gurus' 
      - run: cd /runners && git checkout main 
      - run: echo $HOSTNAME
      - run: pwd
      - run: bash /runners/custom-runner/prd/mostrar.sh
      - run: cd /runners/custom-runner/prd && bash ./mostrar.sh
      - run: pwd
